require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/registers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Register. As you add validations to Register, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Register.create! valid_attributes
      get registers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      register = Register.create! valid_attributes
      get register_url(register)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_register_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      register = Register.create! valid_attributes
      get edit_register_url(register)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Register" do
        expect {
          post registers_url, params: { register: valid_attributes }
        }.to change(Register, :count).by(1)
      end

      it "redirects to the created register" do
        post registers_url, params: { register: valid_attributes }
        expect(response).to redirect_to(register_url(Register.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Register" do
        expect {
          post registers_url, params: { register: invalid_attributes }
        }.to change(Register, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post registers_url, params: { register: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested register" do
        register = Register.create! valid_attributes
        patch register_url(register), params: { register: new_attributes }
        register.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the register" do
        register = Register.create! valid_attributes
        patch register_url(register), params: { register: new_attributes }
        register.reload
        expect(response).to redirect_to(register_url(register))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        register = Register.create! valid_attributes
        patch register_url(register), params: { register: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested register" do
      register = Register.create! valid_attributes
      expect {
        delete register_url(register)
      }.to change(Register, :count).by(-1)
    end

    it "redirects to the registers list" do
      register = Register.create! valid_attributes
      delete register_url(register)
      expect(response).to redirect_to(registers_url)
    end
  end
end
